### ISSUE TITLE
Document double events for pod-to-pod is expected

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/honeycomb-network-agent#115]
We suspect the agent could emit two events for an HTTP request/response cycle:
* one incoming to the k8s Service or Ingress
* one between the k8s Service/Ingress and the pod actually servicing that request

There's another scenario where two k8s nodes each running the agent would each emit an event for the same request/response TCP stream between pods running on them.

**Comment by robbkidd** [comment]
Possible implementation idea to differentiate Pod tcp streams from Service/Ingress:
* interrogate k8s metadata for pods-on-this-node
* use those pods' IPs as input to the capture filter to match only those IPs
* update the packet source regularly as the k8s cache is refreshed

**Comment by MikeGoldsmith** [comment]
Confirmed we receive duplicate events from services and pods. Pods is likely to be more interesting but service routing could be useful for debugging.

Consider a configuration option to toggle on/off service level events -- probably default to off.

**Comment by MikeGoldsmith** [comment]
This is also seen when using load balancers between pods.

**Comment by pkanal** [comment]
Thinking of the standard setting being that incoming requests within a cluster will be dropped. They should be annotated and have an option to opt-in to seeing them

**Comment by pkanal** [comment]
Definition of Done for this issue: document how it currently works.
