### ISSUE TITLE
confirm behavior under resource constraint

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-network-agent#193]
Test with resource limits in local deployment and then in kibble/dogfood - what happens when it hits the limit? Does it simply restart gracefully (temporary loss of telemetry) or have a larger consequence (impact cluster health)?

**Comment by JamieDanielson** [comment]
In local testing on docker-desktop, agent pods were OOM killed and new ones came up on their own, with no similar restarts happening on other services. Next step is to try this out in a bigger cluster out of local docker.

**Comment by MikeGoldsmith** [comment]
Associated to showing a warning when no resource limits are set when installing the helm chart
- https://github.com/honeycombio/helm-charts/pull/298

**Comment by MikeGoldsmith** [comment]
Confirmed pods are OOM terminated in an EKS cluster if they reach resource limits with new pods then scheduled.

A pod is marked as [overcommited](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-types) when trying to request more resource than it's limited to and is a processed managed by the k8s schedular.
