### ISSUE TITLE
Load test HTTP request count does not come close to events received by Honeycomb

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-network-agent#209]
Following up from above, I don't think this is something new. I've worked back through our releases and each of them drop some portion of traffic.

Observed using echoserver and via apache benchmark with following command:
`ab -n 500 -c 10 -k http://localhost:80/echo_body\={agent_version}`

I've opened the following ticket to understand why / how much is not picked up.

              I re-ran my tests incase there was a caching issue as I hadn't seen telemetry go missing before.

I used echo server with 2 replicas and was events coming into Honeycomb:
<img width="1309" alt="image" src="https://github.com/honeycombio/honeycomb-network-agent/assets/3481731/41d5de82-7352-46de-b966-7363fa5c21c4">

However, the numbers do not match up with what locust things it's sent
<img width="526" alt="image" src="https://github.com/honeycombio/honeycomb-network-agent/assets/3481731/b732b281-79ec-4ab2-a089-e0816662969d">

After more fiddling, I can definitely see some traffic is being lost. I hit the end point manually once, wait then 5 more times.
<img width="541" alt="image" src="https://github.com/honeycombio/honeycomb-network-agent/assets/3481731/a30da051-5ee9-4a63-9a6f-ddd1d82751d2">

This shows the one call, then only 2/5.

_Originally posted by @MikeGoldsmith in https://github.com/honeycombio/honeycomb-network-agent/issues/194#issuecomment-1725399774_

**Comment by loshz** [comment]
I can look into this.

**Comment by robbkidd** [comment]
After chatting this morning, the gang's decided to close this research issue when #307 merges. 

We plan to add smoke testing of output next (#78) and with that, a bit of research for how we might include benchmarking agent components over time.
