### ISSUE TITLE
Include k8s node name in emitted events

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/honeycomb-network-agent#217]
**Is your feature request related to a problem? Please describe.**

It is unclear from an event in v0.0.16-alpha which node saw a particular HTTP event. We've got source and destination IPs (and maybe pod names if those IPs map to pods), but there's no node identifier.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeGoldsmith** [comment]
Fixed in #224
