### ISSUE TITLE
k8s pod name sometimes wrong for the IP?

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-network-agent#223]
[kibble query](https://ui.honeycomb.io/kibble/environments/kibble/datasets/kubernetes-ebpf-agent/result/fgcXGwy5fhc) --- looks like some pod names (coredns) don't make sense for the IP range

**Comment by MikeGoldsmith** [comment]
As found in https://github.com/honeycombio/honeycomb-network-agent/pull/194#issuecomment-1731120872 - k8s pods who's deployment uses `hostnetwork=true` share the node IP.

However, coredns doesn't seem to be deployed with a shared node IP.
