### ISSUE TITLE
Duplicate OTel semconv attributes

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-network-agent#292]
OTel is updating some semconv values, with SDKs having to upgrade. To help marry telemetry from two sources that use different keys for the same data, we could duplicate the values into both old and new keys.

              Our libhoney implementation uses `HTTPRequestMethodKey`, which is the newer (not-yet-stable) version. This `HTTPMethod` is technically deprecated in semconv, but is still the consistent key used in OTel until the http semconv is declared stable.
I'm wondering if we should duplicate here now in preparation for those later semconv changes - and also for anyone who may try both libhoney and otel types? - as opposed to only having the old key. 🤔 
Doing that seems to be more than a simple copy though, looks like the new key is specific to the method (e.g. `HTTPRequestMethodGet` and `HTTPRequestMethodPost`).

_Originally posted by @JamieDanielson in https://github.com/honeycombio/honeycomb-network-agent/pull/290#discussion_r1366082634_

**Comment by JamieDanielson** [comment]
closed by #306
