### ISSUE TITLE
Test in various k8s distros

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-network-agent#3]
Linux host distributions / managed services to test with:
- [x] [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine) (GKE)
  - Works with a **Standard cluster**
  - Does not work with Autopilot as it does not support `hostNetwork=true`
- [x] [Azure Kubernetes Servie](https://azure.microsoft.com/en-us/products/kubernetes-service/) (AKS)
- [x] Amazon EKS - Bottle rocket
- [x] Amazon EKS - Amazon linux
- [ ] ~Amazon EKS - [Fargate](https://aws.amazon.com/fargate/)~
  - Fargate only supports `SYS_PTRACE` capabilities 
- [x] Ubuntu 20.04 (EC2)

Moving the following to separate tasks that can be done at a later time
- #255

Output: list of supported platforms in readme
- #256

**Comment by robbkidd** [comment]
Regarding OpenShift (copied from internal message):
```
The 2 things were kernel compatibility and the presence/absence of certain Linux headers that needed to be mounted from the host which required rootlike access from the container.
- Red hat didn't have a new enough kernel. Updated that.
- Red hat's Linux kernel headers directory was different from all the managed k8s Linuxes so the deployment had to be adjusted.
- Openshift's ability to do rootlike things is diminished or blocked by policy in most open shift deployments that I encountered. These were at big financial companies and federal agencies so policy overrides usefulness more often than not.
```

**Comment by JamieDanielson** [comment]
[Fargate does not allow](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_KernelCapabilities.html) `NET_RAW` capabilities so agent does not work there.

> **Note**
> Tasks launched on AWS Fargate only support adding the `SYS_PTRACE` kernel capability.

Tested to confirm using AWS Fargate in EKS 2023-09-28

**Comment by vreynolds** [comment]
Verified v0.0.19-alpha on GKE 1.27.3. You have to use a Standard cluster (as opposed to Autopilot), because _enabling hostNetwork is not allowed in Autopilot_.

**Comment by MikeGoldsmith** [comment]
Confirmed AKS works with @martinjt
