### ISSUE TITLE
Convert custom assember stats into metrics

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-network-agent#74]
There is a custom [stats struct](https://github.com/honeycombio/honeycomb-ebpf-agent/blob/main/assemblers/tcp_assembler.go#L19) that is part of TcpAssembler that is updated while receiving & decoding TCP data. These would be better suited to a metrics solution (eg OTel metrics when we get there).

**Comment by robbkidd** [comment]
We do this now! ᕕ( ᐛ )ᕗ
