### ISSUE TITLE
Add example helm chart

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-network-agent#87]
**Is your feature request related to a problem? Please describe.**

Many people choose to use helm charts when deploying to k8s; we even use one in internal dogfooding!

**Describe the solution you'd like**

Add a simple helm chart in this repo. Later we can move it to a dedicated repo for easier releasing, etc.

**Comment by MikeGoldsmith** [comment]
PR adding helm chart here:
- https://github.com/honeycombio/helm-charts/pull/292
