### ISSUE TITLE
Revisit configuration

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-network-agent#93]
Values from Flags aren't being parsed anymore. This means we don't get expected values. Config is also spread over env vars and command line args.

Options:
- Move config to files (eg yaml or toml)
- Standardise on env vars or command line args

We should also review config options and decide if we need and is the default useful?

Also:

- Follow-up from #142 
  - make tickers configurable
  - make stats dataset configurable
  - move dataset and other similar config to config file

**Comment by JamieDanielson** [comment]
Config items have been refactored and cleaned up in #197
